In [14]:
from sklearn.datasets import load_iris

iris = load_iris()
print('鸢尾花数据集:\n',iris)

鸢尾花数据集:
 {'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.

In [15]:
print('查看数据集描述:\n',iris['DESCR'])

查看数据集描述:
 .. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== =

In [16]:
print('查看特征值的名字:\n',iris.feature_names)

查看特征值的名字:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [17]:
print('查看特征值：\n',iris.data,iris.data.shape)

查看特征值：
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [21]:
from sklearn.model_selection import train_test_split

#将数据集划分成训练用和测试用两部分
#参数传入数据集的特征值数据和目标值数据，测试集部分数据占比test_size，随机数种子
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2,
                                                random_state=22
                                                )
print('训练集的特征值：\n',x_train,x_train.shape)

训练集的特征值：
 [[4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [5.7 2.8 4.5 1.3]
 [5.  3.4 1.6 0.4]
 [5.1 3.4 1.5 0.2]
 [4.9 3.6 1.4 0.1]
 [6.9 3.1 5.4 2.1]
 [6.7 2.5 5.8 1.8]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 4.7 1.6]
 [5.4 3.9 1.3 0.4]
 [4.4 3.2 1.3 0.2]
 [6.7 3.  5.  1.7]
 [5.6 3.  4.1 1.3]
 [5.7 2.5 5.  2. ]
 [6.5 3.  5.8 2.2]
 [5.  3.6 1.4 0.2]
 [6.1 2.8 4.  1.3]
 [6.  3.4 4.5 1.6]
 [6.7 3.  5.2 2.3]
 [5.7 4.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.  3.5 1.3 0.3]
 [4.8 3.  1.4 0.1]
 [5.5 4.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [5.1 2.5 3.  1.1]
 [6.4 3.2 4.5 1.5]
 [7.3 2.9 6.3 1.8]
 [4.5 2.3 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.  3.3 1.4 0.2]
 [6.2 2.2 4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [4.9 2.4 3.3 1. ]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [5.9 3.2 4.8 1.8]
 [5.4 3.9 1.7 0.4]
 [6.  2.2 4.  1. ]
 [6.4 2.8 5.6 2.1]
 [4.8 3.4 1.9 0.2]
 [6.4 3.1 5.5 1.8]
 [5.9 3.  4.2 1.5]
 [6.5 3.  5.5 1.8]
 [6.  2.9 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [

## 特征工程

### 第一步：特征提取

#### 字典数据特征抽取

In [41]:
#语法：
#实例化转换器
sklearn.feature_extraction.DictVectorizer(spars=True)  #spars指定使用稀疏矩阵
#将字典数据特征值化，返回稀疏矩阵
DictVectorizer.fit_transform(X)
#返回特征名字
DictVectorizer.get_feature_names()

NameError: name 'sklearn' is not defined

In [42]:
#案例
from sklearn.feature_extraction import DictVectorizer
#原始数据
data = [{'city':'北京','temperature':'100'},
       {'city':'上海','temperature':'60'},
       {'city':'深圳','temperature':'30'}]

#1. 实例化一个转换器类
transfer = DictVectorizer(sparse=False)
#2. 调用fit_transform(),对字典数据进行特征值化
data_new = transfer.fit_transform(data)
print('data_new:\n',data_new)

data_new:
 [[0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]]


In [40]:
#查看特征名称
print('特征名称:\n',transfer.get_feature_names())

特征名称:
 ['city=上海', 'city=北京', 'city=深圳', 'temperature=100', 'temperature=30', 'temperature=60']


#### 文本特征抽取

In [ ]:
#api

In [45]:
#案例
from sklearn.feature_extraction.text import CountVectorizer
#原始文本数据
data = ['life is short,i like python',
        'life is too long,i dislike python'
       ]

#1. 实例化转换器类
transfer = CountVectorizer()
#2. 调用fit_transform()生成文本特诊矩阵，统计每个样本特诊词出现的个数
data_new = transfer.fit_transform(data)
print('data_new:\n',data_new.toarray())    #使用toarray将稀疏矩阵详细显示
#3. 查看特诊名字
print('特征名字:\n',transfer.get_feature_names())

data_new:
 [[0 1 1 1 0 1 1 0]
 [1 1 1 0 1 1 0 1]]
特征名字:
 ['dislike', 'is', 'life', 'like', 'long', 'python', 'short', 'too']


In [53]:
#案例２：中文笨笨特征抽取，需要使用结巴分词拆分句子成词语
import jieba

def cut_word(text):
    '''
    使用结巴分词进行中文分词
    :param text:
    :return:
    '''
    text = ' '.join(list(jieba.cut(text)))
    return text

#中文文本数据
data = ['一种还是一种今天很残酷，明天更残酷，后天很美好，但绝对大部分是',
       '我们看到的从很远星系来的光是在几百万年之前发出的，']

data_new = []
for sent in data:
    data_new.append(cut_word(sent))
print(data_new)

#实例化一个转换器
transfer = CountVectorizer()

#调用fit_transform
data_final = transfer.fit_transform(data_new)
print('data_new:\n',data_final.toarray())
print('特征名字:\n',transfer.get_feature_names())

['一种 还是 一种 今天 很 残酷 ， 明天 更 残酷 ， 后天 很 美好 ， 但 绝对 大部分 是', '我们 看到 的 从 很 远 星系 来 的 光是在 几百万年 之前 发出 的 ，']
data_new:
 [[2 0 1 0 0 0 1 1 0 1 0 2 0 1 1 1]
 [0 1 0 1 1 1 0 0 1 0 1 0 1 0 0 0]]
特征名字:
 ['一种', '之前', '今天', '光是在', '几百万年', '发出', '后天', '大部分', '我们', '明天', '星系', '残酷', '看到', '绝对', '美好', '还是']


In [55]:
#案例３:tf-idf特征抽取
#在某一个类别的文章中，某个词出现的次数很多，但是在其他类别的文章中出现很少，
#这些词可以用来做分类文章
#使用tf-idf算法计算出各个关键词的重要程度,数值越大说明越重要
#api:TfidVectorizer()

from sklearn.feature_extraction.text import TfidfVectorizer
#中文文本数据
data = ['一种还是一种今天很残酷，明天更残酷，后天很美好，但绝对大部分是',
       '我们看到的从很远星系来的光是在几百万年之前发出的，']

data_new = []
for sent in data:
    data_new.append(cut_word(sent))
print(data_new)

#实例化一个转换器
transfer = TfidfVectorizer()

#调用fit_transform
data_final = transfer.fit_transform(data_new)
print('data_new:\n',data_final.toarray()) #toarray()将稀疏矩阵详细显示
print('特征名字:\n',transfer.get_feature_names())

['一种 还是 一种 今天 很 残酷 ， 明天 更 残酷 ， 后天 很 美好 ， 但 绝对 大部分 是', '我们 看到 的 从 很 远 星系 来 的 光是在 几百万年 之前 发出 的 ，']
data_new:
 [[0.51639778 0.         0.25819889 0.         0.         0.
  0.25819889 0.25819889 0.         0.25819889 0.         0.51639778
  0.         0.25819889 0.25819889 0.25819889]
 [0.         0.37796447 0.         0.37796447 0.37796447 0.37796447
  0.         0.         0.37796447 0.         0.37796447 0.
  0.37796447 0.         0.         0.        ]]
特征名字:
 ['一种', '之前', '今天', '光是在', '几百万年', '发出', '后天', '大部分', '我们', '明天', '星系', '残酷', '看到', '绝对', '美好', '还是']


### 第二步：数据预处理

#### 均值移除

均值移除：让样本矩阵的每一列的平均值为０，标准差为１
api:A = sp.scale(array)　　　　#array为原数组

In [25]:
#案例
import sklearn.preprocessing as sp
import numpy as np

raw_samples = np.array([
    [17,100,4000],
    [20,80,5000],
    [23,75,5500]
])

std_samples = sp.scale(raw_samples)
print(std_samples)
print('\n')
print(std_samples.mean(axis=0))
print('\n')
print(std_samples.std(axis=0))

[[-1.22474487  1.38873015 -1.33630621]
 [ 0.         -0.46291005  0.26726124]
 [ 1.22474487 -0.9258201   1.06904497]]


[ 0.00000000e+00 -3.70074342e-17  5.18104078e-16]


[1. 1. 1.]


#### 范围缩放

将样本矩阵中的每一列的最小值设为相同的区间，统一各列特征值的范围，
一般情况下会把特征值缩放至[0,1]区间

api:
#创建MinMax缩放器
mms = sp.MinMaxScale(feature_range=(0,1))
#调用mms对象的方法执行缩放操作，返回缩放过后的结果
result = mms.fit_transform(原始样本矩阵)

In [ ]:
#案例
raw_samples = np.array([
    [17,100,4000],
    [20,80,5000],
    [23,75,5500]
])

print(raw_samples)

mms_samples = raw_samples.copy()


#### 独热编码one hot encoder

为样本特征的每个值建立一个由一个１和若干个０组成的序列，
用该序列对所有的特征值进行编码

In [ ]:
#语法
#创建一个独热编码器
# sparse： 是否使用紧缩格式（稀疏矩阵）
# dtyle：  数据类型
ohe = sp.OneHotEncoder(sparse=是否采用紧缩格式, dtype=数据类型)
# 对原始样本矩阵进行训练，得到编码字典
encode_dict = ohe.fit(原始样本矩阵)
# 调用encode_dict字典的transform方法 对数据样本矩阵进行独热编码
result = encode_dict.transform(原始样本矩阵)

In [35]:
#案例
raw_samples = np.array([
    [17., 100., 4000],
    [20., 80., 5000],
    [23., 75., 5500]])
# 创建独热编码器
ohe = sp.OneHotEncoder(sparse=False, dtype=int,categories='auto')
# 用独特编码器对原始样本矩阵做独热编码
ohe_dict = ohe.fit(raw_samples)
ohe_samples = ohe_dict.transform(raw_samples)
ohe_samples

array([[1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1]])

In [36]:
ohe_samples = ohe.fit_transform(raw_samples)
ohe_samples

array([[1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1]])

#### 归一化

主要用于处理小规模精确化数据
为了让所有的特征的权重对结果的影响一致，
将每一列的特征值转换成固定的区间内(经常为(0-1),也可以自己设定)

In [56]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = pd.read_csv('文件路径')
#查看dataframe的所有行＆前三列的数据
data = data.iloc[:,:3]
print('data:\n',data)

#1. 实例化一个转换器类
transfer = MinMaxScaler(feature_range=[0,1])

#2. 调用fit_transform进行归一化
data_new = transfer.fit_transform(data)
print('data_new:\n',data_new)

SyntaxError: invalid syntax (<ipython-input-56-b0e15a783e6a>, line 4)

#### 标准化

比归一化更为通用

将ndarray数组每一列数据都聚集在均值为0,标准差为１的附近

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('文件路径')
#查看dataframe的所有行＆前三列的数据
data = data.iloc[:,:3]
print('data:\n',data)

#1. 实例化一个转换器类
transfer = StandardScaler(data)

#2. 调用fit_transform进行标准化
data_new = transfer.fit_transform(data)
print('data_new:\n',data_new)

### 第三步：特征降维

#### 方法１：特征选择

##### 特征选择的方法１:方差选择法(低方差特征过滤)

原理：当特征相近时，他们的方差也是相近的(接近于0)，通过过滤低方差达到特征选择的目的

API

In [ ]:
from sklearn.feature_selection import VarianceThreshold
#1.读取数据
pd.read_csv("csv数据文件")
#2.实例化一个转换器类
transfer = VarianceThreshold(threshold=2)
#3.调用fit_transform
data_new = transfer.fit_transform(data)
print('data_new:n',data_new)

##### 特征选择的方法２：pearsonr相关系数法

数学原理：
步骤１．使用皮尔孙相关系数，查看两个特征间的相关性(越接近-1表示负相关越大，越接近+1表示正相关越大)
步骤２：使用PCA降维

In [ ]:
'''计算pearsonr相关系数'''
from scipy.stats import pearsonr

r = pearsonr(data['特征列１','特征列２'])

#### 方法２：主成分分析(pca降维)

In [2]:
from sklearn.decomposition import PCA
#1.获取数据
data = [[2,8,4,5],
        [6,3,0,8],
        [5,4,9,1]]
#2. 实例化一个转换器类,将４个特征转为2个特征
transfer = PCA(n_components=2)

#3.调用fit_transform()
data_new = transfer.fit_transform(data)
print('data_new:\n',data_new)

data_new:
 [[ 1.28620952e-15  3.82970843e+00]
 [ 5.74456265e+00 -1.91485422e+00]
 [-5.74456265e+00 -1.91485422e+00]]


###### ｐca降维案例：预测instacart超市用户下一步将会买哪些东西

1.数据准备：
   1. 订单与商品信息表：order_products_prior.csv
   字段:order_id,product_id
   2. 商品信息表：products.csv表
   字段：product_id,aisle_id(商品类别)
   3. 用户订单信息表:orders.csv
   字段：order_id,user_id
   4. 商品所属具体物品类别表：aisles.csv
   字段：aisle_id,aisle

2.合并表：将user_id和aisle(商品类别)放到同一张表中，处理成：行索引为user_id,列索引为商品类别(特征)

3.找到user_id和aisle(表示商品类别)之间的关系
4.pca特征降维

In [ ]:
import pandas as pd

#1.获取数据
order_products = pd.read_csv('order_productes_prior.csv')
products = pd.read_csv('products.csv')
orders = pd.read_csv('orders.csv')
aisles = pd.read_csv('aisles.csv')

#2.合并表，将字段user_id和aisle放到一张表中
#因为products.csv表和aisles.csv表中都有aisle_id,先将这两个表合并
tab1 = pd.merge(aisles,products,on='aisle_id')
#然后tab1表和order_products表根据字段products_id合并(默认inner连接)
tab2 = pd.merge(tab1,order_products,on='product_id')
#最后tab2表和order_products表根据order_id字段合并，得到有user_id和aisle字段的表
tab3 = pd.merge(tab2,orders,on='order_id')

#3.找到user_id和aisle之间的关系,
#使用交叉表,按照user_id,针对不同的aisle统计数量
table = pd.crosstab(tab3['user_id'],tab3['aisle'])

#4.pca降维
from sklearn.decomposition import PCA
#实例化转换器类,保留95%的数据
transfer = PCA(n_components=0.95)
#调用fit_transform
data_new = transfer.fit_transform(table)

### 第三步：使用机器学习算法进行训练获取模型

#### 分类算法

##### １．k-近邻算法
优点：简单，易于理解
缺点：需要选择好k值，属于懒惰算法，计算量大，时间复杂度高，只适合与小数据量使用

###### knn算法案例：对sklearn的鸢尾花数据集进行分类

In [4]:
#1. 获取鸢尾花数据集
from sklearn.datasets import load_iris
iris = load_iris()
#2. 使用sklearn划分数据集
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 random_state=6)
#3. 特征工程:标准化
from sklearn.preprocessing import  StandardScaler
transfer = StandardScaler()
#对训练集进行标准化
x_train = transfer.fit_transform(x_train)
#对测试集进行标准化
x_test = transfer.transform(x_test)

#4. knn算法预估器(算法)进行模型训练
from sklearn.neighbors import KNeighborsClassifier
#生成预估器对象
estimator = KNeighborsClassifier()
#对k值进行调优：加入网格搜索和交叉验证
from sklearn.model_selection import GridSearchCV
#参数准备，给出预备的k值
param_dict = {'n_neighbors':[1,3,5,7,9,11]}
estimator = GridSearchCV(estimator,param_grid=param_dict,cv=10)
#将训练集的特征值和目标值放进来进行训练
estimator.fit(x_train,y_train)

#5.模型评估
#方法１：直接比对真实值和预测值
#获取预测值
y_predict = estimator.predict(x_test)
#比对,返回True越多说明模型越成功
print('直接比对真实值和预测值：\n',y_test == y_predict)
#方法２：计算准确率
score = estimator.score(x_test,y_test)
print('准确率:\n',score)

#最佳参数
print('最佳参数:\n',estimator.best_params_)
#最佳结果
print('最佳结果:\n',estimator.best_score_)
#最佳估计器
print('最佳估计器：\n',estimator.best_estimator_)
#交叉验证结果
print('交叉验证结果:\n',estimator.cv_results_)

直接比对真实值和预测值：
 [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True]
准确率:
 0.9473684210526315
最佳参数:
 {'n_neighbors': 5}
最佳结果:
 0.9732142857142857
最佳估计器：
 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
交叉验证结果:
 {'mean_fit_time': array([0.00074785, 0.00058436, 0.00043838, 0.00037799, 0.00046234,
       0.00042078]), 'std_fit_time': array([4.73110502e-04, 3.03020541e-04, 1.38584090e-04, 5.12299561e-05,
       3.37450548e-04, 1.19581901e-04]), 'mean_score_time': array([0.00307391, 0.00190549, 0.00121212, 0.00109873, 0.00109513,
       0.00116651]), 'std_score_time': array([2.22851995e-03, 1.21863413e-03, 3.59040332e-04, 7.50393986e-05,
       1.21867024e-04, 2.43258911e-04]), '

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


###### knn算法案例：facebook签到数据

In [1]:
import pandas as pd

#获取数据
data = pd.read_csv('./heima_files/day02/data_FBlocation/train.csv')
data

row_id       x       y  accuracy    time    place_id
0                0  0.7941  9.0809        54  470702  8523065625
1                1  5.9567  4.7968        13  186555  1757726713
2                2  8.3078  7.0407        74  322648  1137537235
3                3  7.3665  2.5165        65  704587  6567393236
4                4  4.0961  1.1307        31  472130  7440663949
...            ...     ...     ...       ...     ...         ...
29118016  29118016  6.5133  1.1435        67  399740  8671361106
29118017  29118017  5.9186  4.4134        67  125480  9077887898
29118018  29118018  2.9993  6.3680        67  737758  2838334300
29118019  29118019  4.0637  8.0061        70  764975  1007355847
29118020  29118020  7.4523  2.0871        17  102842  7028698129

[29118021 rows x 6 columns]

In [2]:
#案例中为了方便，缩小下数据集,只选取2<x<2.5 & 1<y<1.5之间的记录(工作中不需要)
data = data.query('x > 2 & x < 2.5 & y > 1 & y <1.5')
data

row_id       x       y  accuracy    time    place_id
112            112  2.2360  1.3655        66  623174  7663031065
180            180  2.2003  1.2541        65  610195  2358558474
367            367  2.4108  1.3213        74  579667  6644108708
874            874  2.0822  1.1973       320  143566  3229876087
1022          1022  2.0160  1.1659        65  207993  3244363975
...            ...     ...     ...       ...     ...         ...
29115112  29115112  2.1889  1.2914       168  721885  4606837364
29115204  29115204  2.1193  1.4692        58  563389  2074133146
29115338  29115338  2.0007  1.4852        25  765986  6691588909
29115464  29115464  2.4132  1.4237        61  151918  7396159924
29117493  29117493  2.2948  1.0504        81   79569  1168869217

[83197 rows x 6 columns]

In [3]:
#数据处理思路：
#1.将时间戳转为年月日
dates = pd.to_datetime(data['time'],unit='s')
dates = pd.DatetimeIndex(dates)
dates

DatetimeIndex(['1970-01-08 05:06:14', '1970-01-08 01:29:55',
               '1970-01-07 17:01:07', '1970-01-02 15:52:46',
               '1970-01-03 09:46:33', '1970-01-06 19:49:38',
               '1970-01-06 13:33:24', '1970-01-02 22:49:55',
               '1970-01-04 14:30:10', '1970-01-07 16:57:44',
               ...
               '1970-01-02 09:24:50', '1970-01-01 10:29:34',
               '1970-01-09 11:38:46', '1970-01-02 03:42:14',
               '1970-01-04 22:02:44', '1970-01-09 08:31:25',
               '1970-01-07 12:29:49', '1970-01-09 20:46:26',
               '1970-01-02 18:11:58', '1970-01-01 22:06:09'],
              dtype='datetime64[ns]', name='time', length=83197, freq=None)

In [10]:
#将day ,weekday, hour添加到原始数据集中去
data['day'] = dates.day
data['weekday'] = dates.weekday
data['hour'] = dates.hour
data

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead



row_id       x       y  accuracy    time    place_id  day  \
112            112  2.2360  1.3655        66  623174  7663031065    8   
180            180  2.2003  1.2541        65  610195  2358558474    8   
367            367  2.4108  1.3213        74  579667  6644108708    7   
874            874  2.0822  1.1973       320  143566  3229876087    2   
1022          1022  2.0160  1.1659        65  207993  3244363975    3   
...            ...     ...     ...       ...     ...         ...  ...   
29115112  29115112  2.1889  1.2914       168  721885  4606837364    9   
29115204  29115204  2.1193  1.4692        58  563389  2074133146    7   
29115338  29115338  2.0007  1.4852        25  765986  6691588909    9   
29115464  29115464  2.4132  1.4237        61  151918  7396159924    2   
29117493  29117493  2.2948  1.0504        81   79569  1168869217    1   

          weekday  hour  
112             3     5  
180             3     1  
367             2    17  
874             4    15  
1022            5     9  
...           ...   ...  
29115112        4     8  
29115204        2    12  
29115338        4    20  
29115464        4    18  
29117493        3    22  

[83197 rows x 9 columns]

In [11]:
#过滤掉签到次数少的地点(因为目的是分析签到多的location)
#根据place_id进行分组聚合，查看各place_id的签到次数
#并过滤掉签到次数row_id<4的place_id数据
place_count = data.groupby('place_id').count()['row_id']
place_count

place_id
1012165853     1
1013991737     3
1014605271    28
1015645743     4
1017236154    31
              ..
9988815170     1
9992113332     1
9993074125     2
9994257798    25
9996671132    18
Name: row_id, Length: 2514, dtype: int64

In [12]:
data_final = data[data['place_id'].isin(place_count[place_count > 3].index.values)]
data_final
# isin(place_count(place_count > 3).index.values)

row_id       x       y  accuracy    time    place_id  day  \
112            112  2.2360  1.3655        66  623174  7663031065    8   
367            367  2.4108  1.3213        74  579667  6644108708    7   
874            874  2.0822  1.1973       320  143566  3229876087    2   
1022          1022  2.0160  1.1659        65  207993  3244363975    3   
1045          1045  2.3859  1.1660       498  503378  6438240873    6   
...            ...     ...     ...       ...     ...         ...  ...   
29115112  29115112  2.1889  1.2914       168  721885  4606837364    9   
29115204  29115204  2.1193  1.4692        58  563389  2074133146    7   
29115338  29115338  2.0007  1.4852        25  765986  6691588909    9   
29115464  29115464  2.4132  1.4237        61  151918  7396159924    2   
29117493  29117493  2.2948  1.0504        81   79569  1168869217    1   

          weekday  hour  
112             3     5  
367             2    17  
874             4    15  
1022            5     9  
1045            1    19  
...           ...   ...  
29115112        4     8  
29115204        2    12  
29115338        4    20  
29115464        4    18  
29117493        3    22  

[80910 rows x 9 columns]

In [13]:
#筛选特征值和目标值
#特征值
x = data_final[['x','y','accuracy','day','weekday','hour']]
#目标值
y = data_final['place_id']
#-------以上为数据清洗，获取特征值和目标值的部分------------------

In [14]:
#---------以下为特征工程部分----------
#数据集划分
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y)
x_train

x       y  accuracy  day  weekday  hour
23007922  2.4485  1.0138        77    7        2    14
25785263  2.2503  1.3005        66    7        2     5
18005463  2.0899  1.1891        72    3        5    14
17892524  2.4850  1.4253        54    9        4    13
10356407  2.4246  1.2065        62    5        0    16
...          ...     ...       ...  ...      ...   ...
6573759   2.3887  1.3054        29    4        6    17
17184298  2.3864  1.0222        65    9        4    21
3047468   2.3707  1.4906        66    6        1    10
26133408  2.0718  1.1736       201    9        4    10
23864929  2.3936  1.1778        72    7        2     1

[60682 rows x 6 columns]

In [17]:
from sklearn.preprocessing import StandardScaler     #特征预处理
from sklearn.neighbors import KNeighborsClassifier  #机器学习算法
from sklearn.model_selection import GridSearchCV  #特征降维

In [18]:
#特征工程：特征预处理－标准化
transfer =StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [22]:
#-----以下为机器学习算法部分-----
#knn算法预估器
estimator = KNeighborsClassifier()

#加入网格搜索与交叉验证
#参数准备
param_dict = {'n_neighbors':[3,5,7]}
estimator = GridSearchCV(estimator,param_grid=param_dict,cv=3)
estimator.fit(x_train,y_train)

#模型评估
#方法１：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print('y_predict:\n',y_predict)
print('直接比对真实值和预测值:\n',y_test == y_predict)

#方法２：计算准确率
score = estimator.score(x_test,y_test)
print('准确率为:\n',score)

#最佳参数：best_params
print('最佳参数:\n',estimator.best_params_)
#最佳结果
print('最佳结果:\n',estimator.best_score_)
#最佳估计器:best_estimator
print('最佳估计器:\n',estimator.best_estimator_)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


y_predict:
 [6438240873 7810150060 7038685199 ... 1663763627 1663763627 2607294907]
直接比对真实值和预测值:
 26165420     True
12759338    False
18740715    False
3509883     False
1168648     False
            ...  
21462544     True
11946677    False
11755634     True
10429475     True
24300335    False
Name: place_id, Length: 20228, dtype: bool
准确率为:
 0.3649396875617955
最佳参数:
 {'n_neighbors': 5}
最佳结果:
 0.33579974292211856
最佳估计器:
 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')


##### 朴素贝叶斯算法

###### 朴素贝叶斯算法案例：２０类新闻分类

思路：
1. 获取数据(sklearn内置的大样本数据集)
2. 划分数据集
3. 特征工程
    文本特征抽取
4. 朴素贝叶斯预估器流程
5. 模型评估

In [ ]:
from sklearn.datasets import fetch_20newsgroups  #导入数据集
#获取数据
news = fetch_20newsgroups(subset='all')#subset='all'指明训练集和测试集都要

#划分数据集
x_train,x_test,y_train,y_test = train_test_split(news.data,news.target)
#特征工程：文本特征抽取
from sklearn.feature_extraction.text import TfidfVectorizer
transfer = TfidfVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transfer(x_test)
#朴素贝叶斯算法预估器流程
from sklearn.naive_bayes import MultinomialNB
estimator = MultinomialNB()
estimator.fit(x_train,y_train)
#模型评估
#方法１：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print('y_predict:\n',y_predict)
print('直接比对真实值和预测值:n',y_test == y_predict)

#方法２：计算准确率,将
score = estimator.score(x_test,y_test)
